# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 23:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blogger',
        ),
        migrations.AddField(
            model_name='blog',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blogger.Blogger'),
            preserve_default=False,
        ),
    ]
