# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 04:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='link',
            new_name='page',
        ),
    ]
