# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0004_auto_20180516_0402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='blogger',
            old_name='joined',
            new_name='date_joined',
        ),
        migrations.RenameField(
            model_name='blogpost',
            old_name='post_date',
            new_name='posted_date',
        ),
    ]
