# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-12 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogger', '0005_auto_20180516_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='page',
            field=models.SlugField(blank=True, default=None, max_length=110),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='blogger.BlogCategory'),
        ),
    ]
